service: product-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  stackName: product-service-dev
  httpApi:
    cors: true

  environment:
    SQS_URL:
      Ref: SQSQueue
    SNS_ARN:
      Ref: SNSTopic

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:eu-west-1:378686460370:table/Product_Catalog"
        - Effect: "Allow"
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:eu-west-1:378686460370:table/Stocks"
        - Effect: "Allow"
          Action: "sqs: *"
          Resource: 
            - Fn::GetAtt: [ SQSQueue, Arn ]
        - Effect: "Allow"
          Action: "sns: *"
          Resource: 
            Ref: SNSTopic

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: createProductTopic
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: rm.levsha@gmail.com
        Protocol: email
        TopicArn:
          Ref: SNSTopic

functions:
  getProductsById:
    handler: handler.getProductsById
    events:
      - httpApi:
          method: get
          path: /products/{id}

  getProductsList:
    handler: handler.getProductsList
    events:
      - httpApi:
          path: /products
          method: get

  createProduct:
    handler: handler.createProduct
    events:
      - httpApi:
          path: /products
          method: post 

  catalogBatchProcess:
    handler: handler.catalogBatchProcess
    events: 
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - SQSQueue
              - Arn