service: product-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  stackName: product-service-dev
  httpApi:
    cors: true
    
functions:
  getProductsById:
    handler: handler.getProductsById
    events:
      - httpApi:
          method: get
          path: /products/{id}

  getProductsList:
    handler: handler.getProductsList   
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
        Resource: "arn:aws:dynamodb:eu-west-1:378686460370:table/Product_Catalog"
    events:
      - httpApi:
          path: /products
          method: get
